### ISSUE TITLE
Multi Language Buttons

### ISSUE THREAD

**Issue by tigurius8180** [getgrav/grav-plugin-snipcart#20]
Hi! I was thinking to improve the multi language grav to this plugins. 

Something like adding the file to the root plugin:
`languages.yaml`

Then inside this files define all the labels can be modifyed by the language site. For example:

```
es:
  PLUGIN_SNIPCART:
    CARD: Carrito
    ADD_TO_CARD: 'Añadir al carrito'
    DETAIL: 'Detalle'

ca:
  PLUGIN_SNIPCART:
    CARD: Cistell
    ADD_TO_CARD: 'Afegir al cistell'
    DETAIL: 'Detalls'
```

Then into :
`snipcart_detail_item.html`

Add the template for the use the Language traductor tag:
` {{ "PLUGIN_SNIPCART.ADD_TO_CARD"|t|e }}`

in case of the old "Add" static label.

Any ideas or working progress were welcome!

Best regards,
